name: content_store
publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cbl: ^1.0.0-beta.10
  collection: ^1.15.0
  meta: ^1.7.0
  synchronized: ^3.0.0

dev_dependencies:
  cbl_dart: ^1.0.0-beta.1
  lints: ^1.0.1
  test: ^1.19.3
